'use client';

import Link from 'next/link';
import { AlertTriangle, ArrowLeft, Ban, CalendarCheck, CheckCircle2, ChevronRight, Clock3, FileText, Globe2, LockKeyhole, Mail, Phone, Scale, ShieldCheck, Stethoscope, UserCheck } from 'lucide-react';

const sections = [
  ['aceptacion', 'Aceptación y alcance'], ['servicio', 'El servicio SaludClick'], ['cuentas', 'Cuentas de usuario'],
  ['uso', 'Uso permitido'], ['citas', 'Citas y cancelaciones'], ['salud', 'Relación médico-paciente'],
  ['privacidad', 'Privacidad y datos'], ['pagos', 'Pagos y tarifas'], ['propiedad', 'Propiedad intelectual'],
  ['cuenta', 'Suspensión y cierre'], ['cambios', 'Cambios a estos términos'], ['ley', 'Ley aplicable y contacto'],
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#f6f9fc] text-slate-900">
      <header className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-6xl px-4 py-5 sm:px-6 lg:px-8"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-blue-700 hover:text-blue-800"><ArrowLeft className="h-4 w-4" /> Volver a SaludClick</Link></div></header>
      <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8">
        <div className="grid gap-8 lg:grid-cols-[230px_minmax(0,1fr)] lg:items-start">
          <aside className="hidden lg:sticky lg:top-6 lg:block">
            <p className="mb-3 text-xs font-bold uppercase tracking-wider text-slate-400">En este documento</p>
            <nav className="space-y-1">{sections.map(([id, label]) => <a key={id} href={`#${id}`} className="block rounded-lg px-3 py-2 text-sm font-medium text-slate-600 transition hover:bg-blue-50 hover:text-blue-700">{label}</a>)}</nav>
            <div className="mt-6 rounded-2xl border border-blue-100 bg-blue-50 p-4"><ShieldCheck className="mb-3 h-5 w-5 text-blue-600" /><p className="text-sm font-bold text-blue-950">¿Tienes dudas?</p><p className="mt-1 text-xs leading-5 text-blue-800">Escríbenos antes de utilizar la plataforma.</p><a href="mailto:legal@saludclick.com" className="mt-3 inline-flex text-xs font-bold text-blue-700 hover:underline">Contactar soporte</a></div>
          </aside>

          <article className="min-w-0">
            <section className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-[#123baf] via-[#087ec3] to-[#0ca78f] p-6 text-white shadow-xl shadow-blue-900/10 sm:p-10">
              <div className="absolute -right-16 -top-20 h-56 w-56 rounded-full bg-white/10 blur-2xl" /><div className="relative">
                <div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-white/15 ring-1 ring-white/20"><Scale className="h-6 w-6" /></div>
                <p className="text-sm font-bold uppercase tracking-[0.18em] text-white/70">SaludClick · República Dominicana</p>
                <h1 className="mt-3 max-w-2xl text-3xl font-black tracking-tight sm:text-5xl">Términos y condiciones</h1>
                <p className="mt-4 max-w-2xl text-sm leading-6 text-white/80 sm:text-base">Estas condiciones explican cómo puedes utilizar nuestra plataforma de citas y cuáles son las responsabilidades de SaludClick, pacientes y profesionales.</p>
                <div className="mt-6 flex flex-wrap gap-2 text-xs font-semibold text-white/80"><span className="rounded-full border border-white/20 bg-white/10 px-3 py-1.5">Última actualización: 6 de octubre de 2026</span><span className="rounded-full border border-white/20 bg-white/10 px-3 py-1.5">Lectura aproximada: 6 minutos</span></div>
              </div>
            </section>

            <div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 sm:p-5"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-600" /><div><p className="font-bold text-amber-950">Antes de comenzar</p><p className="mt-1 text-sm leading-6 text-amber-900">SaludClick facilita la búsqueda y gestión de citas; no sustituye una evaluación médica. Si tienes una emergencia, llama al 9-1-1 o acude al centro de salud más cercano.</p></div></div></div>

            <div className="mt-5 rounded-2xl border border-slate-200 bg-white p-4 lg:hidden"><p className="mb-3 text-xs font-bold uppercase tracking-wider text-slate-400">Ir a una sección</p><div className="grid grid-cols-1 gap-1 sm:grid-cols-2">{sections.map(([id, label]) => <a key={id} href={`#${id}`} className="flex items-center justify-between rounded-lg px-2 py-2 text-sm font-semibold text-blue-700 hover:bg-blue-50"><span>{label}</span><ChevronRight className="h-4 w-4" /></a>)}</div></div>

            <div className="mt-8 space-y-5">
              <TermsSection id="aceptacion" icon={FileText} number="01" title="Aceptación y alcance"><p>Al acceder, registrarte o utilizar SaludClick, aceptas estos Términos y Condiciones y nuestra <Link href="/privacy" className="font-bold text-blue-700 hover:underline">Política de Privacidad</Link>. Si no estás de acuerdo, no debes utilizar la plataforma.</p><p>Debes proporcionar información veraz y tener capacidad legal para aceptar estas condiciones. Si utilizas SaludClick en nombre de una organización, declaras tener autorización para hacerlo.</p></TermsSection>
              <TermsSection id="servicio" icon={Globe2} number="02" title="El servicio SaludClick"><p>SaludClick es una plataforma digital que conecta pacientes con profesionales y centros de salud para facilitar la búsqueda, solicitud, confirmación y gestión de citas.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Feature text="Buscar profesionales y centros de salud" /><Feature text="Solicitar, revisar o cancelar citas" /><Feature text="Consultar recetas y documentos disponibles" /><Feature text="Recibir comunicaciones relacionadas con el servicio" /></div><p className="mt-4 text-sm text-slate-500">Las funciones disponibles pueden variar según el tipo de cuenta, el profesional y la disponibilidad del servicio.</p></TermsSection>
              <TermsSection id="cuentas" icon={UserCheck} number="03" title="Cuentas de usuario"><p>Para utilizar determinadas funciones debes crear una cuenta. Eres responsable de mantener actualizada tu información, proteger tus credenciales y avisarnos si detectas un acceso no autorizado.</p><p>Las cuentas de profesionales pueden requerir revisión de identidad, credenciales y demás información profesional antes de publicar o utilizar ciertas funciones.</p></TermsSection>
              <TermsSection id="uso" icon={ShieldCheck} number="04" title="Uso permitido y prohibiciones"><p>Debes utilizar SaludClick de manera legal, segura y respetuosa. No está permitido:</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><Restriction text="Suplantar a otra persona o proporcionar datos falsos." /><Restriction text="Acceder a cuentas o información sin autorización." /><Restriction text="Usar bots, scraping o automatizaciones no autorizadas." /><Restriction text="Publicar contenido fraudulento, abusivo o difamatorio." /><Restriction text="Intentar interrumpir o vulnerar la seguridad del servicio." /><Restriction text="Utilizar la plataforma para fines ilegales." /></div></TermsSection>
              <TermsSection id="citas" icon={CalendarCheck} number="05" title="Citas, cambios y cancelaciones"><p>La disponibilidad, duración, modalidad, precio y condiciones de cada cita dependen del profesional o centro de salud. Revisa los detalles antes de confirmar.</p><ul className="mt-4 space-y-3"><Bullet>Una solicitud de cita no siempre equivale a una confirmación; verifica el estado dentro de la plataforma.</Bullet><Bullet>Las cancelaciones y cambios deben realizarse desde los canales habilitados y pueden estar sujetos a la política del profesional.</Bullet><Bullet>Las inasistencias o cancelaciones repetidas pueden generar restricciones razonables para proteger la disponibilidad del servicio.</Bullet><Bullet>Los recordatorios son una ayuda y no sustituyen tu responsabilidad de revisar tus citas.</Bullet></ul></TermsSection>
              <TermsSection id="salud" icon={Stethoscope} number="06" title="Relación médico-paciente"><div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm leading-6 text-rose-900"><strong>SaludClick no presta servicios médicos.</strong> No diagnostica, prescribe ni garantiza resultados clínicos. La relación asistencial, la evaluación, el diagnóstico, el tratamiento y las indicaciones corresponden al profesional de salud.</div><p className="mt-4">La información de perfiles se ofrece para facilitar la búsqueda, pero debes valorar si el profesional es adecuado para tus necesidades y solicitar aclaraciones directamente cuando corresponda.</p></TermsSection>
              <TermsSection id="privacidad" icon={LockKeyhole} number="07" title="Privacidad y datos personales"><p>El tratamiento de datos personales y de la información relacionada con la atención se explica en nuestra <Link href="/privacy" className="font-bold text-blue-700 hover:underline">Política de Privacidad</Link>. Al usar funciones de SaludClick, autorizas el tratamiento necesario para prestar el servicio, sujeto a la normativa aplicable de la República Dominicana.</p><p>Las cookies esenciales se utilizan para sesión y seguridad. Las tecnologías no esenciales requieren una elección del usuario mediante el panel de cookies.</p></TermsSection>
              <TermsSection id="pagos" icon={FileText} number="08" title="Pagos, tarifas y reembolsos"><p>El registro y las funciones básicas para pacientes pueden ser gratuitos. Si una cita, servicio o producto tiene un costo, el importe y las condiciones aplicables deben mostrarse antes de confirmar.</p><p>Los pagos, reembolsos, cargos por cancelación o comisiones pueden depender del profesional, centro de salud o proveedor de pago correspondiente. Conserva tus comprobantes y contacta primero al canal indicado en la transacción.</p></TermsSection>
              <TermsSection id="propiedad" icon={FileText} number="09" title="Propiedad intelectual"><p>SaludClick, su nombre, logotipo, diseño, software, contenido y estructura pertenecen a SaludClick o a sus licenciantes. Puedes utilizar la plataforma únicamente para sus fines previstos y no puedes copiarla, modificarla, distribuirla, descompilarla o explotarla sin autorización escrita.</p><p>Conservas los derechos sobre el contenido que publiques, pero nos otorgas la autorización necesaria para almacenarlo, mostrarlo y procesarlo con el fin de operar el servicio.</p></TermsSection>
              <TermsSection id="cuenta" icon={Ban} number="10" title="Suspensión y cierre de cuentas"><p>Podemos limitar, suspender o cerrar una cuenta cuando sea necesario para proteger a los usuarios, investigar fraude, cumplir una obligación legal, atender riesgos de seguridad o responder a una infracción de estos términos.</p><p>También puedes solicitar el cierre de tu cuenta. Algunas obligaciones, registros o información podrán conservarse cuando exista una razón legal, de seguridad o de gestión de la relación asistencial.</p></TermsSection>
              <TermsSection id="cambios" icon={Clock3} number="11" title="Cambios a estos términos"><p>Podemos actualizar estos términos para reflejar cambios en el servicio, requisitos legales o mejoras de seguridad. Publicaremos la versión vigente indicando la fecha de actualización y, cuando el cambio sea material, procuraremos notificarlo por canales razonables.</p><p>Si continúas utilizando la plataforma después de la entrada en vigor de una actualización, se aplicará la versión vigente. Si no estás de acuerdo, puedes dejar de utilizar el servicio y solicitar el cierre de tu cuenta.</p></TermsSection>
              <TermsSection id="ley" icon={Scale} number="12" title="Ley aplicable y contacto"><p>Estos términos se interpretan conforme a las leyes de la República Dominicana. Cualquier controversia se someterá a las autoridades y tribunales competentes, sin perjuicio de los derechos irrenunciables que correspondan al usuario.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><a href="mailto:legal@saludclick.com" className="flex items-center gap-3 rounded-xl bg-blue-50 p-4 text-sm font-semibold text-blue-900 hover:bg-blue-100"><Mail className="h-5 w-5 text-blue-600" /> legal@saludclick.com</a><a href="tel:+18293861067" className="flex items-center gap-3 rounded-xl bg-slate-50 p-4 text-sm font-semibold text-slate-800 hover:bg-slate-100"><Phone className="h-5 w-5 text-slate-600" /> +1 829 386 1067</a></div><p className="mt-4 text-sm text-slate-500">Dirección de contacto: Santo Domingo, República Dominicana.</p></TermsSection>
            </div>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/privacy" className="inline-flex h-12 flex-1 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-5 text-sm font-bold text-slate-700 hover:bg-slate-50"><LockKeyhole className="h-4 w-4" /> Ver política de privacidad</Link><Link href="/register" className="inline-flex h-12 flex-1 items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 text-sm font-bold text-white shadow-sm hover:bg-blue-700"><UserCheck className="h-4 w-4" /> Crear cuenta</Link></div>
          </article>
        </div>
      </main>
    </div>
  );
}

function TermsSection({ id, icon: Icon, number, title, children }: { id: string; icon: any; number: string; title: string; children: React.ReactNode }) {
  return <section id={id} className="scroll-mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-start gap-4"><div className="hidden h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-blue-700 sm:flex"><Icon className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-blue-600"><span>{number}</span><span className="h-px w-6 bg-blue-200" /></div><h2 className="mt-1 text-xl font-black tracking-tight text-slate-950 sm:text-2xl">{title}</h2><div className="mt-4 space-y-3 text-sm leading-7 text-slate-600 sm:text-base">{children}</div></div></div></section>;
}

function Feature({ text }: { text: string }) { return <div className="flex items-start gap-2 rounded-xl bg-slate-50 p-3 text-sm font-semibold text-slate-700"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />{text}</div>; }
function Restriction({ text }: { text: string }) { return <div className="flex items-start gap-2 rounded-xl border border-rose-100 bg-rose-50/70 p-3 text-sm text-slate-700"><Ban className="mt-0.5 h-4 w-4 shrink-0 text-rose-500" />{text}</div>; }
function Bullet({ children }: { children: React.ReactNode }) { return <li className="flex items-start gap-3"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-blue-600" /><span>{children}</span></li>; }
